/* eslint-disable @typescript-eslint/no-var-requires */
import { getStorybookUI, configure, addDecorator, addParameters } from '@storybook/react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
// import '@storybook/addon-ondevice-notes/register';
// import '@storybook/addon-ondevice-controls/register';
// import '@storybook/addon-ondevice-backgrounds/register';
// import '@storybook/addon-ondevice-actions/register';
import { decorators, parameters } from './preview';
import { AppRegistry } from 'react-native';
const loadStories = require('../../../../.storybook/story-loader.js');

// import stories
configure(() => {
    loadStories();
}, module);

// Refer to https://github.com/storybookjs/storybook/tree/master/app/react-native#start-command-parameters
// To find allowed options for getStorybookUI
const StorybookUIRoot = getStorybookUI({
    //@ts-ignore
    asyncStorage: AsyncStorage,
    onDeviceUI: false,
    disableWebsockets: true,
    shouldPersistSelection: true,
});

/* do not change this file, it is auto generated by storybook. */
if (decorators) {
    decorators.forEach((decorator) => addDecorator(decorator));
}

if (parameters) {
    addParameters(parameters);
}

// If you are using React Native vanilla and after installation you don't see your app name here, write it manually.
// If you use Expo you can safely remove this line.
AppRegistry.registerComponent('Storybook', () => StorybookUIRoot);

export default StorybookUIRoot;
