#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -n "${CI}" ]; then
    echo "CI, exiting"
    exit 0
fi

# Extract emoji from commit title so commitlint rule doesnt break
head -n1 "$1" | cut -d' ' -f2- | yarn commitlint
