#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Extract emoji from commit title so commitlint rule doesnt break
commit="$1"
cat "$commit"
stripped=$(cut -d' ' -f2- "$commit")
echo "$stripped"
echo "$stripped" | cut -d' ' -f2- | commitlint
