name: CI

on:
    push:
        tags:
            - '*'
        branches: [main]
    pull_request:
        branches: [main, develop]
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_STOP_AGENTS_ON_FAILURE: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 5
    NEXT_TELEMETRY_DISABLED: 1

jobs:
    main:
        name: Main Job
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        strategy:
            matrix:
                os: [ubuntu-latest]
                include:
                    - os: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Cache Rust
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ${{ github.workspace }}/target/
                      ${{ github.workspace }}/dist/
                      ${{ github.workspace }}/node_modules/
                  key: ${{ matrix.os }}-node-cargo-${{ hashFiles('**/Cargo.lock', '**/yarn.lock') }}
                  restore-keys: ${{ matrix.os }}-node-cargo

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy,

            - name: Install Tauri Dependencies
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Derive appropriate SHAs for base and head for `nx affected` commands
              uses: nrwl/nx-set-shas@v3

            - name: Install Dependencies
              run: yarn install

            - name: Linting Workspace
              run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx workspace-lint

            - name: Checking Workspace Format
              run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx format:check

            - name: Start Nx Cloud Distributed Task Execution
              run: npx nx-cloud start-ci-run

            - name: Distributed Tasks
              run: |
                  yarn ci:build --base=$NX_BASE --head=$NX_HEAD &
                  yarn ci:lint  --base=$NX_BASE --head=$NX_HEAD &
                  yarn ci:format --base=$NX_BASE --head=$NX_HEAD &
                  yarn ci:test  --base=$NX_BASE --head=$NX_HEAD &
                  yarn ci:e2e --base=$NX_BASE --head=$NX_HEAD

            - name: Stop Agents
              run: npx nx-cloud stop-all-agents

    agents:
        name: Agent
        runs-on: ${{ matrix.os }}
        timeout-minutes: 60
        strategy:
            matrix:
                os: [ubuntu-latest]
                agent: [1, 2, 3, 4, 5]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache Rust
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ${{ github.workspace }}/target/
                      ${{ github.workspace }}/dist/
                      ${{ github.workspace }}/node_modules/
                  key: ${{ matrix.os }}-node-cargo-${{ hashFiles('**/Cargo.lock', '**/yarn.lock') }}
                  restore-keys: ${{ matrix.os }}-node-cargo

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy,

            - name: Install Tauri Dependencies (ubuntu only)
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Install Dependencies
              run: yarn install

            - name: Start Agent ${{ matrix.agent }}
              run: npx nx-cloud start-agent
