name: CI

on:
    push:
        tags:
            - '*'
        branches: [main]
    pull_request:
        branches: [main, develop]
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

env:
    NEXT_TELEMETRY_DISABLED: 1

jobs:
    main:
        name: Main Job
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        strategy:
            matrix:
                os: [ubuntu-latest]
                include:
                    - os: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Derive appropriate SHAs for base and head for `nx affected` commands
              uses: nrwl/nx-set-shas@v3

            - name: Cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ${{ github.workspace }}/target/
                      ${{ github.workspace }}/dist/
                      ${{ github.workspace }}/node_modules/
                  key: ${{ matrix.os }}-node-cargo-${{ hashFiles('**/Cargo.lock', '**/yarn.lock') }}
                  restore-keys: ${{ matrix.os }}-node-cargo

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Install Tauri Dependencies
              if: matrix.os == 'ubuntu-latest'
              run: |
                  if ! git diff --quiet --exit-code --diff-filter=ACM "$NX_BASE" "$NX_HEAD" apps/desktop; then
                      sudo apt-get update
                      sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
                  fi

            - name: Install Dependencies
              run: yarn install

            - name: Linting Workspace
              run: npx nx workspace-lint

            - name: Checking Workspace Format
              run: npx nx format:check

            - name: Build
              run: yarn ci:build --base=$NX_BASE --head=$NX_HEAD

            - name: Lint
              run: yarn ci:lint --base=$NX_BASE --head=$NX_HEAD

            - name: Format
              run: yarn ci:format --base=$NX_BASE --head=$NX_HEAD

            - name: Test
              run: yarn ci:test --base=$NX_BASE --head=$NX_HEAD

            - name: E2E
              run: yarn ci:e2e --base=$NX_BASE --head=$NX_HEAD
