name: ci

on:
    push:
        tags:
            - '*'
        branches: [main]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

env:
    NEXT_TELEMETRY_DISABLED: 1
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_STOP_AGENTS_ON_FAILURE: true
    NX_EXEC: 'npx nx affected --nx-bail --base=$NX_BASE --head=$NX_HEAD --exclude=desktop --parallel=$NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT --target'
    RUST: false
    RUST_BUILT: false

jobs:
    web:
        name: Export Web
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Update
              run: sudo apt-get update

            - name: Install Protocol Buffer Dependencies
              run: sudo apt-get install -y protobuf-compiler libprotobuf-dev

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Checkout [Pull Request]
              uses: actions/checkout@v3
              if: github.event_name == 'pull_request'
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Checkout [Main]
              uses: actions/checkout@v3
              if: github.event_name != 'pull_request'
              with:
                  fetch-depth: 0

            - name: Derive SHAs
              uses: nrwl/nx-set-shas@v3

            - name: Node Cache
              id: node_cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      node_modules/
                  key: ubuntu-latest-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ubuntu-latest-node-

            - name: Rust Cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ubuntu-latest-cargo-${{ hashFiles('Cargo.lock') }}
                  restore-keys: ubuntu-latest-cargo

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Format Workspace
              if: needs.agents.result != 'failure' && needs.agents.result != 'cancelled' && needs.agents.result != 'skipped'
              run: |
                  NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- npx nx format:check --libs-and-apps
                  cargo fmt --all --check

            - name: Lint Workspace
              if: needs.agents.result != 'failure' && needs.agents.result != 'cancelled' && needs.agents.result != 'skipped'
              run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- npx nx workspace-lint

            - name: Export Web
              run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx export --skip-nx-cache

            - name: Upload Web
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist

    desktop:
        name: Build Desktop
        runs-on: ${{ matrix.platform }}
        needs: [web]
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-12, ubuntu-latest, windows-latest]
        steps:
            - name: Install Dependencies (ubuntu)
              if: matrix.platform == 'ubuntu-latest'
              run: sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf protobuf-compiler libprotobuf-dev

            - name: Install Dependencies (macos)
              if: matrix.platform == 'macos-12'
              run: brew install protobuf

            - name: Install Python (windows)
              if: matrix.platform == 'windows-latest'
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Install Dependencies (windows)
              if: matrix.platform == 'windows-latest'
              run: |
                  python -m pip install --upgrade pip
                  pip install protobuf

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Checkout [Pull Request]
              uses: actions/checkout@v3
              if: github.event_name == 'pull_request'
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Checkout [Main]
              uses: actions/checkout@v3
              if: github.event_name != 'pull_request'
              with:
                  fetch-depth: 0

            - name: Node Cache
              id: node_cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      node_modules/
                  key: ${{ matrix.platform }}-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ${{ matrix.platform }}-node-

            - name: Rust Cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ matrix.platform }}-cargo-${{ hashFiles('Cargo.lock') }}
                  restore-keys: ${{ matrix.platform }}-cargo-

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Download Web
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Build Tauri App
              run: yarn tauri build

            - name: Package App (macos only)
              if: matrix.platform == 'macos-12'
              run: tar cvf target/release/bundle/macos/capital-tracker.app.tar target/release/bundle/macos/capital-tracker.app

            - name: Upload Desktop (ubuntu-latest)
              if: matrix.platform == 'ubuntu-latest'
              uses: actions/upload-artifact@v3
              with:
                  name: linux-desktop
                  path: |
                      target/release/bundle/appimage/*.AppImage
                      target/release/bundle/deb/*.deb

            - name: Upload Desktop (macos-12)
              if: matrix.platform == 'macos-12'
              uses: actions/upload-artifact@v3
              with:
                  name: macos-desktop
                  path: |
                      target/release/bundle/macos/*.app.tar
                      target/release/bundle/dmg/*.dmg

            - name: Upload Desktop (windows-latest)
              if: matrix.platform == 'windows-latest'
              uses: actions/upload-artifact@v3
              with:
                  name: windows-desktop
                  path: |
                      target/release/bundle/msi/*.msi

            - name: Abort Workflow
              if: failure()
              run: |
                  curl -X POST -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel

            - name: Delete Artifacts
              if: failure()
              uses: geekyeggo/delete-artifact@v2
              with:
                  name: '*'

    main:
        name: Main Job
        needs: [web]
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout [Pull Request]
              uses: actions/checkout@v3
              if: github.event_name == 'pull_request'
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Checkout [Main]
              uses: actions/checkout@v3
              if: github.event_name != 'pull_request'
              with:
                  fetch-depth: 0

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Download Web
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Derive SHAs
              uses: nrwl/nx-set-shas@v3

            - name: Node Cache
              id: node_cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      node_modules/
                  key: ubuntu-latest-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ubuntu-latest-node-

            - name: Rust Cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ubuntu-latest-cargo-${{ hashFiles('Cargo.lock') }}
                  restore-keys: ubuntu-latest-cargo

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Start Agents
              if: needs.agents.result != 'failure' && needs.agents.result != 'cancelled' && needs.agents.result != 'skipped'
              run: npx nx-cloud start-ci-run --stop-agents-after=e2e

            - name: Run Agents
              id: agents
              if: needs.agents.result != 'failure' && needs.agents.result != 'cancelled' && needs.agents.result != 'skipped'
              uses: jameshenry/parallel-bash-commands@v1
              with:
                  cmd1: $NX_EXEC build
                  cmd2: $NX_EXEC test
                  cmd3: $NX_EXEC lint
                  cmd4: npx nx affected --base=$NX_BASE --head=$NX_HEAD --parallel=1 --target=e2e

            - name: Stop Agents
              if: always()
              run: npx nx-cloud stop-all-agents

            - name: Abort Workflow
              if: failure()
              run: |
                  curl -X POST -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel

            - name: Delete Artifacts
              if: failure()
              uses: geekyeggo/delete-artifact@v2
              with:
                  name: '*'

    set-agents:
        runs-on: ubuntu-latest
        needs: [web]
        name: Set Agent Matrix
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Calculate Matrix
              id: set-matrix
              shell: bash
              run: |
                  AGENTS_JSON_ARRAY=$(node -e "console.log(JSON.stringify(Array.from(new Array($NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT)).map((_, i) => i + 1)));")
                  echo $AGENTS_JSON_ARRAY
                  echo "matrix=$AGENTS_JSON_ARRAY" >> $GITHUB_OUTPUT

    agents:
        name: Agent ${{ matrix.agent }}
        needs: set-agents
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        strategy:
            matrix:
                agent:
                    - ${{fromJson(needs.set-agents.outputs.matrix)}}
        steps:
            - name: Update
              run: sudo apt-get update

            - name: Install Tauri Dependencies
              run: sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Install Protocol Buffer Dependencies
              run: sudo apt-get install -y protobuf-compiler libprotobuf-dev

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Checkout [Pull Request]
              uses: actions/checkout@v3
              if: github.event_name == 'pull_request'
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Checkout [Main]
              uses: actions/checkout@v3
              if: github.event_name != 'pull_request'
              with:
                  fetch-depth: 0

            - name: Derive SHAs
              uses: nrwl/nx-set-shas@v3

            - name: Restore Node Cache
              id: node_cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      node_modules/
                  key: ubuntu-latest-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ubuntu-latest-node-

            - name: Restore Rust Cache
              id: rust_cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ubuntu-latest-cargo-${{ hashFiles('Cargo.lock') }}
                  restore-keys: ubuntu-latest-cargo

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Download Web
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Run Agent
              run: npx nx-cloud start-agent

            - name: Abort Workflow
              if: failure()
              run: |
                  curl -X POST -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel

            - name: Delete Artifacts
              if: failure()
              uses: geekyeggo/delete-artifact@v2
              with:
                  name: '*'

    deploy:
        name: Deploy Web
        runs-on: ubuntu-latest
        needs: [main, agents]
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Node Cache
              id: node_cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      node_modules/
                  key: ubuntu-latest-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ubuntu-latest-node-

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Download Web
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Deploy to Firebase Hosting Preview on PR
              if: github.event.pull_request.head.repo.full_name == github.repository
              uses: w9jds/firebase-action@master
              with:
                  args: hosting:channel:deploy pr${{ github.event.ref }} --expires 12h
              env:
                  GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIFEMASTERY_8F9C1 }}

            - name: Deploy to Firebase Hosting on Main
              if: github.event_name != 'pull_request' && github.ref_name == 'main'
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIFEMASTERY_8F9C1 }}

            - name: Delete Artifacts
              if: failure()
              uses: geekyeggo/delete-artifact@v2
              with:
                  name: '*'

    release:
        name: Release
        runs-on: ${{ matrix.platform }}
        needs: [desktop, main, agents]
        defaults:
            run:
                shell: bash
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-12, ubuntu-latest, windows-latest]
        steps:
            - name: Download Desktop (ubuntu-latest)
              if: matrix.platform == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/v')
              uses: actions/download-artifact@v3
              with:
                  name: linux-desktop

            - name: Download Desktop (macos-12)
              if: matrix.platform == 'macos-12' && startsWith(github.ref, 'refs/tags/v')
              uses: actions/download-artifact@v3
              with:
                  name: macos-desktop

            - name: Download Desktop (windows-latest)
              if: matrix.platform == 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
              uses: actions/download-artifact@v3
              with:
                  name: windows-desktop

            - name: Release Desktop App (macos-12)
              if: matrix.platform == 'macos-12' && startsWith(github.ref, 'refs/tags/v')
              uses: softprops/action-gh-release@v1
              with:
                  token: ${{ secrets.TAURI_GITHUB_TOKEN }}
                  fail_on_unmatched_files: true
                  files: |
                      macos/*.app.tar
                      dmg/*.dmg

            - name: Release Desktop App (ubuntu-latest)
              if: matrix.platform == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/v')
              uses: softprops/action-gh-release@v1
              with:
                  generate_release_notes: true
                  fail_on_unmatched_files: true
                  token: ${{ secrets.TAURI_GITHUB_TOKEN }}
                  files: |
                      appimage/*.AppImage
                      deb/*.deb

            - name: Release Desktop App (windows-latest)
              if: matrix.platform == 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
              uses: softprops/action-gh-release@v1
              with:
                  token: ${{ secrets.TAURI_GITHUB_TOKEN }}
                  fail_on_unmatched_files: true
                  files: |
                      *.msi

            - name: Delete Artifacts
              if: failure()
              uses: geekyeggo/delete-artifact@v2
              with:
                  name: '*'

    cleanup:
        name: Cleanup
        runs-on: ubuntu-latest
        needs: [deploy, release]
        steps:
            - name: Delete Artifacts
              uses: geekyeggo/delete-artifact@v2
              with:
                  name: '*'
