name: ci

on:
    push:
        tags:
            - '*'
        branches: [main]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_STOP_AGENTS_ON_FAILURE: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NEXT_TELEMETRY_DISABLED: 1
    RUST: false

jobs:
    main:
        name: Main Job
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash
        strategy:
            matrix:
                os: [ubuntu-latest]
        steps:
            - name: Checkout [Pull Request]
              uses: actions/checkout@v3
              if: ${{ github.event_name == 'pull_request' }}
              with:
                ref: ${{ github.event.pull_request.head.sha }}
                fetch-depth: 0

            - name: Checkout [Main]
              uses: actions/checkout@v3
              if: ${{ github.event_name != 'pull_request' }}
              with:
                fetch-depth: 0

            - name: Derive SHAs
              uses: nrwl/nx-set-shas@v3

            - name: Check for affected Rust
              run: |
                  echo "head=$NX_HEAD base=$NX_BASE"
                  if ! git diff --name-only --exit-code --diff-filter=ACDMRT $NX_HEAD $NX_BASE apps/desktop; then
                    echo "RUST=true" >> $GITHUB_ENV
                  fi

            - name: Node Cache
              id: node_cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      node_modules/
                  key: ubuntu-latest-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ubuntu-latest-node-

            - name: Rust Cache
              id: rust_cache
              if: env.RUST == 'true'
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ubuntu-latest-cargo-${{ hashFiles('Cargo.lock') }}
                  restore-keys: ubuntu-latest-cargo

            - name: Install Tauri Dependencies
              if: env.RUST == 'true'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Install Rust Toolchain
              if: env.RUST == 'true'
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Start Agents
              run: npx nx-cloud start-ci-run --stop-agents-on-failure=true --stop-agents-after=e2e

            - name: Format Workspace
              run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- npx nx format:check

            - name: Lint Workspace
              run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- npx nx workspace-lint

            - name: Run Agents
              uses: jameshenry/parallel-bash-commands@v1
              with:
                  cmd1: npx nx affected --base=$NX_BASE --head=$NX_HEAD --parallel=3 --target=build
                  cmd2: npx nx affected --base=$NX_BASE --head=$NX_HEAD --parallel=3 --target=lint
                  cmd3: npx nx affected --base=$NX_BASE --head=$NX_HEAD --parallel=3 --target=format
                  cmd4: npx nx affected --base=$NX_BASE --head=$NX_HEAD --parallel=3 --target=test
                  cmd5: npx nx affected --base=$NX_BASE --head=$NX_HEAD --parallel=3 --target=e2e

            - name: Stop Agents
              if: ${{ always() }}
              run: npx nx-cloud stop-all-agents

    agents:
        name: Agent
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        strategy:
            matrix:
                agent: [1, 2, 3]
        steps:
            - name: Checkout [Pull Request]
              uses: actions/checkout@v3
              if: ${{ github.event_name == 'pull_request' }}
              with:
                ref: ${{ github.event.pull_request.head.sha }}
                fetch-depth: 0

            - name: Checkout [Main]
              uses: actions/checkout@v3
              if: ${{ github.event_name != 'pull_request' }}
              with:
                fetch-depth: 0

            - name: Derive SHAs
              uses: nrwl/nx-set-shas@v3

            - name: Check for affected Rust
              run: |
                  echo "head=$NX_HEAD base=$NX_BASE"
                  if ! git diff --exit-code --diff-filter=ACDMRT $NX_HEAD $NX_BASE apps/desktop; then
                    echo "RUST=true" >> $GITHUB_ENV
                  fi

            - name: Restore Node Cache
              id: node_cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cache/Cypress/
                      node_modules/
                  key: ubuntu-latest-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ubuntu-latest-node-

            - name: Restore Rust Cache
              if: env.RUST == 'true'
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ubuntu-latest-cargo-${{ hashFiles('Cargo.lock') }}
                  restore-keys: ubuntu-latest-cargo

            - name: Install Rust Toolchain
              if: env.RUST == 'true'
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Install Tauri Dependencies
              if: env.RUST == 'true'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Run Agent
              run: npx nx-cloud start-agent
